---
- name: Install and run systemd unit
  hosts: zookeepers
  become: true

  tasks:
    - name: Install systemd unit file
      ansible.builtin.template:
        src: "../templates/zookeeper.service.j2"
        dest: "/etc/systemd/system/zookeeper.service"
        owner: root
        group: root
        mode: "0644"

    - name: systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable & start zookeeper
      ansible.builtin.systemd:
        name: zookeeper
        enabled: true
        state: started
